# Generated by Django 5.1.3 on 2024-11-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=255)),
                ('inscription_complete', models.BooleanField()),
                ('lien_vers_certificat', models.CharField(max_length=2048)),
                ('inscription_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'InscriptionCourse',
            },
        ),
    ]
