[package]
name = "projet_rsa_int"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.12.1"
iced_core = "0.12.1"
rand = "0.8.5"
num-bigint = "0.4.6" 
num-traits = "0.2"
num-primes =  "0.3"
rsa = { version = "0.9.6", features = ["default"] }