# Generated by Django 5.1.3 on 2024-11-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscriptioncourse',
            name='email',
        ),
    ]
