# Generated by Django 5.1.3 on 2024-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioncompte',
            name='inscription_complete',
            field=models.BooleanField(default=False),
        ),
    ]
