# Generated by Django 5.1.3 on 2024-12-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_remove_inscriptioncourse_lien_vers_certificat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioncourse',
            name='certificat_med',
            field=models.FileField(blank=True, null=True, upload_to='siteCourse/media'),
        ),
        migrations.AlterField(
            model_name='inscriptioncourse',
            name='course',
            field=models.CharField(choices=[('5km', '5 km'), ('10km', '10 km'), ('semi-marathon', 'Semi-marathon'), ('marathon', 'Marathon')], max_length=255),
        ),
    ]
