# Generated by Django 5.1.3 on 2024-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_alter_inscriptioncourse_certificat_med_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioncourse',
            name='inscription_complete',
            field=models.BooleanField(default=False),
        ),
    ]
