# Generated by Django 5.1.3 on 2024-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_alter_inscriptioncourse_inscription_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioncourse',
            name='certificat_med',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
