# Generated by Django 5.1.3 on 2024-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0007_remove_inscriptioncourse_certificat_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioncourse',
            name='certificat_med',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
