# Generated by Django 5.1.3 on 2024-12-04 14:55

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0009_alter_inscriptioncourse_certificat_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioncourse',
            name='certificat_med',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='certificats_medicaux/'),
        ),
    ]
