# Generated by Django 5.1.3 on 2024-12-04 16:33

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0011_certificatmedical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioncourse',
            name='certificat_med',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='certificats_medicaux/'),
        ),
        migrations.DeleteModel(
            name='CertificatMedical',
        ),
    ]
