# Generated by Django 5.1.3 on 2024-12-04 17:34

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0013_certificatmedical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptioncourse',
            name='certificat_med',
            field=private_storage.fields.PrivateFileField(default=False, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='certificats_medicaux/'),
        ),
    ]
